kobo:
    dbfile: .kobo\KoboReader.sqlite
    rootfolder: kobo\ 
    supportedformats: EPUB, EPUB3, FlePub, PDF, MOBI, JPEG, GIF, PNG, BMP, TIFF, TXT, HTML, RTF, CBZ, CBR, FB2
local:
    shelfpath: books\