kobo:
    path: e:\.kobo\
    databasefile: KoboReader.sqlite
    supportedformats: EPUB, EPUB3, FlePub, PDF, MOBI, JPEG, GIF, PNG, BMP, TIFF, TXT, HTML, RTF, CBZ, CBR
local:
    shelfpath: books\
